apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: motd-backend
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: motd-backend
    networking.knative.dev/visibility: cluster-local
spec:
  source:
    git:
      url: https://github.com/alexandreroman/motd-backend.git
      ref:
        branch: main
  env:
  - name: SPRING_CONFIG_IMPORT
    value: optional:configtree:${SERVICE_BINDING_ROOT}/motd-config/
  serviceClaims:
  - name: motd-config
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: motd-backend-config
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 2Gi
      cpu: 1000m
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "0"
      autoscaling.knative.dev/maxScale: "3"
      autoscaling.knative.dev/target: "5"
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/window: "120s"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
